<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <UseWindowsForms>true</UseWindowsForms>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>Assets\app.ico</ApplicationIcon>
        <ApplicationIcon Condition="'$(Configuration)' == 'Debug'">Assets\app-dev.ico</ApplicationIcon>
        <AssemblyName>NdCrosshair</AssemblyName>
        <RootNamespace>NdCrosshair.App</RootNamespace>
        <Product>ND Crosshair</Product>
        <Authors>nowaaak</Authors>
        <Description>Custom crosshair overlay for Windows games</Description>
        <Copyright>Copyright (c) 2026 nowaaak</Copyright>
        <Version>1.0.0</Version>
        <NoWarn>$(NoWarn);WFO0003</NoWarn>
        <StartupObject>NdCrosshair.App.Program</StartupObject>
    </PropertyGroup>

    <ItemGroup>
        <ApplicationDefinition Remove="App.xaml" />
        <Page Include="App.xaml" />
    </ItemGroup>

    <ItemGroup>
        <Using Remove="System.Windows.Forms" />
        <Using Remove="System.Drawing" />
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Assets\app.ico" />
        <Resource Include="Assets\app-dev.ico" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NdCrosshair.Core\NdCrosshair.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Velopack" Version="1.2.158" />
    </ItemGroup>

</Project>
